const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {execFileSync}=require('node:child_process');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.setContent('<base href="http://zero.local/"><button id="open">Открыть редактор</button>');
 await page.addStyleTag({path:root+'/assets/zero-editor.css'});
 await page.addScriptTag({path:root+'/assets/zero-model.js'});await page.addScriptTag({path:root+'/assets/zero-editor.js'});
 await page.evaluate(()=>{window.options={html:'<b>Legacy</b>'};document.querySelector('#open').onclick=()=>ZeroEditor.open(window.options,data=>window.options={...window.options,zero:data});});
 const click=a=>page.locator(`[data-action="${a}"]`).click();
 const field=(k)=>page.locator(`[data-field="${k}"]`);
 const edit=async(k,v)=>{await field(k).fill(String(v));await field(k).press('Tab');};
 await page.locator('#open').click();await click('add-text');await edit('text','Hello <world>');
 await edit('name','Headline');await edit('x',80);await edit('y',80);
 await click('add-shape');await edit('fill','#dbeafe');await click('down');
 await page.locator('[data-select]').filter({hasText:'Headline'}).click();
 await click('mobile');await edit('x',32);await edit('fontSize',18);
 await click('desktop');assert.equal(await field('x').inputValue(),'80');
 await click('duplicate');assert.equal(await page.locator('.ze-layer-row').count(),3);
 await page.keyboard.press('ControlOrMeta+z');assert.equal(await page.locator('.ze-layer-row').count(),2);
 await page.keyboard.press('ControlOrMeta+Shift+z');assert.equal(await page.locator('.ze-layer-row').count(),3);
 await click('delete');assert.equal(await page.locator('.ze-layer-row').count(),2);
 await page.locator('[data-select]').filter({hasText:'Headline'}).click();
 // Moving and resizing uses screen coordinates divided by zoom.
 await field('zoom').selectOption('0.5');await field('snap').uncheck();
 const el=page.locator('.ze-element.is-selected');let box=await el.boundingBox();
 await page.mouse.move(box.x+30,box.y+20);await page.mouse.down();await page.mouse.move(box.x+70,box.y+40,{steps:5});await page.mouse.up();
 assert.equal(await field('x').inputValue(),'160');assert.equal(await field('y').inputValue(),'120');
 const handle=page.locator('.ze-se');box=await handle.boundingBox();
 await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+40,box.y+box.height/2+20,{steps:5});await page.mouse.up();
 assert.equal(await field('width').inputValue(),'360');assert.equal(await field('height').inputValue(),'140');
 // Locks prevent keyboard move and deletion; hidden layers leave the canvas.
 await page.locator('.ze-layer-row.is-selected [data-toggle="locked"]').click();
 await page.keyboard.press('ArrowRight');await page.keyboard.press('Delete');assert.equal(await page.locator('.ze-layer-row').count(),2);assert.equal(await field('x').inputValue(),'160');
 await page.locator('.ze-layer-row.is-selected [data-toggle="locked"]').click();
 await page.locator('.ze-layer-row.is-selected [data-toggle="hidden"]').click();assert.equal(await page.locator('.ze-element').count(),1);
 await page.locator('.ze-layer-row.is-selected [data-toggle="hidden"]').click();
 await click('add-button');await edit('text','Подробнее');await edit('href','https://example.com');await edit('y',340);
 await field('name').fill('Primary button');await click('apply');assert.equal(await page.locator('.ze-dialog').isVisible(),false);const saved=await page.evaluate(()=>window.options);assert.equal(saved.html,'<b>Legacy</b>');assert.equal(saved.zero.layers.length,3);
 assert.equal(saved.zero.layers.find(l=>l.name==='Headline').mobile.x,32);
 await page.locator('#open').click();await click('add-image');
 await page.route('http://zero.local/admin/upload.php',route=>route.fulfill({status:200,headers:{'Access-Control-Allow-Origin':'*'},contentType:'application/json',body:JSON.stringify({url:'/uploads/test.svg'})}));
 await page.route('http://zero.local/uploads/test.svg',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10" fill="blue"/></svg>'}));
 await page.locator('[data-upload]').setInputFiles({name:'test.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"/>')});
 await page.waitForFunction(()=>document.querySelector('[data-field="src"]')?.value==='/uploads/test.svg');
 assert.equal(await page.locator('.ze-element.is-selected img').getAttribute('src'),'/uploads/test.svg');
 await page.unroute('http://zero.local/admin/upload.php');
 await page.route('http://zero.local/admin/upload.php',route=>route.fulfill({status:400,headers:{'Access-Control-Allow-Origin':'*'},contentType:'application/json',body:JSON.stringify({error:'Upload rejected'})}));
 await page.locator('[data-upload]').setInputFiles({name:'bad.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')});
 await page.waitForFunction(()=>document.querySelector('.ze-error')?.textContent==='Upload rejected');
 assert.equal(await field('src').inputValue(),'/uploads/test.svg');
 page.once('dialog',d=>d.accept());await click('cancel');assert.deepEqual(await page.evaluate(()=>window.options),saved);
 await page.locator('#open').click();await page.screenshot({path:'/tmp/zero-editor-desktop.png'});
 await click('mobile');await page.screenshot({path:'/tmp/zero-editor-mobile.png'});await click('cancel');
 const php='require $argv[1]; echo renderZeroBlock(json_decode(stream_get_contents(STDIN),true));';
 const html=execFileSync('php',['-r',php,root+'/includes/zero-render.php'],{input:JSON.stringify(saved.zero),encoding:'utf8'});
 await page.setContent(`<div id="container" style="width:1000px">${html}</div>`);await page.addStyleTag({path:root+'/assets/zero-public.css'});
 assert.equal(await page.locator('.zero-public-desktop').isVisible(),true);assert.equal(await page.locator('.zero-public-mobile').isVisible(),false);
 assert.equal(await page.locator('.zero-public-desktop').innerText(),'Hello <world>\nПодробнее');
 await page.evaluate(()=>document.querySelector('#container').style.width='375px');assert.equal(await page.locator('.zero-public-mobile').isVisible(),true);assert.equal(await page.locator('.zero-public-desktop').isVisible(),false);
 const text=page.locator('.zero-public-mobile .zero-public-layer').nth(1);assert.equal(await text.evaluate(el=>getComputedStyle(el).fontSize),'18px');
 assert.deepEqual(errors,[]);console.log('PASS browser: add/edit, independent mobile, reorder, duplicate, history, drag, resize, lock, hide, apply, reopen, upload success/failure, cancel, safe public output and responsive switching');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
